config/routes.rb
Rails.application.routes.draw do
  
  root :to =>'home#index'
  devise_for :users,:controllers => { :registrations =>'users/registrations'}
  resources :users, except: [:create, :new, :show]
  resources :meal_categories, except: [:show]
  resources :meals
  resources :orders
  get 'carts/show'

  post 'order_meals', to: 'order_meals#create'
  patch 'order_meals', to: 'order_meals#update'
  delete 'order_meals', to: 'order_meals#destroy'
  
end

app/views/shared/_backOffice_header.html.erb
<%= render 'shared/notice' %>

<div class="container-fluid position-relative" id="image-backoffice">
  
  <div class="container">
    <nav class="navbar navbar-expand-lg navbar-light">
      <%= link_to 'DinnerDash', root_path, class: 'navbar-brand text-white' %>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse flex-row-reverse" id="navbarNavAltMarkup">
        <div class="navbar-nav">
          <% if current_user.admin? %>
          <span class="nav-item nav-link text-warning">backoffice</span>
          <% end %>
          <%= link_to 'Perfil', edit_user_registration_path, class: 'nav-item nav-link text-white' %>
          <%= link_to "Sign Out", destroy_user_session_path, :method => :delete, class: 'nav-item nav-link text-white' %>
        </div>
      </div>
    </nav>
  </div>

  <div class="jumbotron text-white title bg-transparent m-0">
      <h1>BackOffice</h1>
      <h3>Gerencie pedidos, refeições e mais.</h3>
  </div>

</div>

app/views/shared/_backOffice_nav.html.erb
<div class="container-fluid bg-dark">
  <div class="container">
    <ul class="nav nav-tabs">
      <li class="nav-item">
      <%= link_to "Pedidos", orders_path, class: "nav-link text-muted" if !current_page?('/orders')%>
      <%= link_to "Pedidos", orders_path, class: "nav-link active" if current_page?('/orders')%>
      </li>
      <li class="nav-item text-muted">
      <%= link_to "Usuários", users_path, class: "nav-link text-muted" if !current_page?('/users')%>
      <%= link_to "Usuários", users_path, class: "nav-link active" if current_page?('/users')%>
      </li>
      <li class="nav-item text-muted">
      <%= link_to "Refeições", meals_path, class: "nav-link text-muted" if !current_page?('/meals')%>
      <%= link_to "Refeições", meals_path, class: "nav-link active" if current_page?('/meals')%>
      </li>
      <li class="nav-item text-muted">
      <%= link_to "Categorias de Refeições", meal_categories_path, class: "nav-link text-muted" if !current_page?('/meal_categories') %>
      <%= link_to "Categorias de Refeições", meal_categories_path, class: "nav-link active" if current_page?('/meal_categories')%>
      </li>
    </ul>
  </div>
</div>

app/views/shared/_footer.html.erb
<footer class="bg-light py-2" >
  <div class="container text-muted">
    <h5>DinnerDash | todos os dias reservados</h5>
  </div>
</footer>

app/views/shared/_form_error.html.erb
<% if obj.errors.any? %>
    <div id="error_explanation">
      <ul class="alert alert-danger">
        <div class="container">
          <% obj.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </div>
      </ul>
    </div>
  <% end %>

app/views/shared/_notice.html.erb
<% if flash[:notice] %>
<div id="notice" class="alert alert-success fade show text-center text-dark m-0 p-2">
  <span><%= notice %></span>
  <button type="button" class="close" data-dismiss="alert">
      <span aria-hidden="true">&times;</span>
  </button>
</div>
<% elsif flash[:alert] %>
<div id="notice" class="alert alert-warning fade show text-center text-dark m-0 p-2">
  <span><%= alert %></span>
  <button type="button" class="close" data-dismiss="alert">
      <span aria-hidden="true">&times;</span>
  </button>
</div>
<% end %>