config/routes.rb
Rails.application.routes.draw do
  
  root :to =>'home#index'
  devise_for :users,:controllers => { :registrations =>'users/registrations'}
  resources :users, except: [:create, :new, :show]
  resources :meal_categories, except: [:show]
  resources :meals
  resources :orders
  get 'carts/show'

  post 'order_meals', to: 'order_meals#create'
  patch 'order_meals', to: 'order_meals#update'
  delete 'order_meals', to: 'order_meals#destroy'
  
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    @categories = MealCategory.all
    @cart_item = OrderMeal.new
  end
  
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_cart_row.html.erb
<div class="row">
    <div class="col-xs-8">
      <h4><%= product.name %></h4>
    </div>
    <div class="col-xs-4">

      <%= form_for OrderMeal.new, remote: true, method: :patch do |f| %>
        <h4 class="text-right">Unit Price: <span style="color: green"><%= number_to_currency product.price %></span></h4>
        <div class="row">
          <div class="col-xs-4">
            <%= f.number_field :quantity, value: quantity.to_i, class: "form-control", min: 1 %>
            <%= f.hidden_field :meal_id, value: product.id %>
          </div>
          <div class="col-xs-8 text-right">
            <div class="btn-group">
              <% f.submit "Update Quantity", class: "btn btn-primary" %>
              <%= link_to "Delete", order_meals_path(item), { data: { confirm: "Are you sure you wish to delete the product '#{product.name}' from your cart?" }, method: :delete, remote: true, class: "btn btn-danger" } %>
            </div>
          </div>
        </div>
        <h4 class="text-right">Total Price: <span style="color: green"><%= number_to_currency (product.price * quantity.to_i) %></span></h4>
      <% end %>
    </div>

  </div>

app/views/home/_cart_text.html.erb
<h3>Preço total do pedido: <span class="text-success"><%= number_to_currency cart_total_price %></span></h3>

app/views/home/_header.html.erb
<% if user_signed_in? && current_user.admin? %>
<%= controller.redirect_to users_path  %>
<% end %>

<%= render 'shared/notice' %>

<div class="container-fluid position-relative" id="image-homepage">
  
  <div class="container">
    <nav class="navbar navbar-expand-lg navbar-light">
      <%= link_to 'DinnerDash', root_path, class: 'navbar-brand text-white' %>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse flex-row-reverse" id="navbarNavAltMarkup">
        <div class="navbar-nav">
          <% if user_signed_in? %>
          <%= link_to 'Perfil', edit_user_registration_path, class: 'nav-item nav-link text-white'  %>
          <%= link_to "Sign Out", destroy_user_session_path, :method => :delete, class: 'nav-item nav-link text-white'  %>
          <% else %>
          <%= link_to "Sign In", new_user_session_path, :method => :get, class: 'nav-item nav-link text-white'  %>
          <%= link_to "Sign up", new_user_registration_path, :method => :get, class: 'nav-item nav-link text-white'  %>
          <% end %>
        </div>
      </div>
    </nav>
  </div>

  <div class="jumbotron text-white title bg-transparent m-0">
    <% if user_signed_in? %>
      <h1>Bem Vindo, <%= current_user.name.capitalize %></h1>
      <h3>Escolha sua salada, molho, prato principal, guarnição e bebida.</h3>
    <% else %>
      <h1>Monte seu prato</h1>
      <h3>Escolha sua salada, molho, prato principal, guarnição e bebida.</h3>
    <% end %>
  </div>

</div>

app/views/home/_shopping_cart.html.erb
<% if current_cart.empty? %>
  <p class="alert alert-primary text-center"> Carrinho vazio.</p>
<% else %>
  <% current_cart.each do |item| %>
    <%= render 'home/cart_row', product: Meal.find(item["meal_id"]), quantity: item["quantity"], show_total: true, item: item %>
  <% end %>
<% end %>

app/views/home/index.html.erb
<%= render 'header' %>

<% @categories.each do |category| %>
  <div class="container my-5">
    <h3 class="mb-3 text-muted"><%= category.name %></h3>
    <div class="card-deck">
      <% category.meals.each do |meal| %>
        <div class="card">
          <div class="position-relative">
            <%= image_tag "#{meal.image}", alt: '', class: 'card-img-top' %>
            <div class="card-img-overlay h-100 d-flex flex-column justify-content-end p-0">
              <h5 class="bg-dark-50 mb-0 text-white p-2"><%= meal.name %></h5>
            </div>
          </div>
          <div class="card-body">
            <h6 class="card-subtitle mb-2 text-muted"><%= meal.description %></h6>
            <p class="card-text text-success">R$ <%= number_with_precision(meal.price, :precision => 2) %> por porção</p>
            <div class="form-group">
              <%= form_for @cart_item, remote: true do |f| %>
                <div class="form-group">
                  <%= f.label :quantity, "Quantity", class: 'card-text text-muted' %>
                  <%= f.number_field :quantity, value: 1, min: 1, step: 1, class: 'form-control' %>
                </div>
                <%= f.hidden_field :meal_id, value: meal.id %>
                <%= f.submit "Submit", disable_with: 'Submiting...', class: 'btn btn-success btn-block' %>
              <% end %>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
<% end %>


<div class="container">
  <div class="card">
    <div class="card-body">
      <h5 class="card-title">Finalizou o seu pedido?</h5>
      <h6 class="card-subtitle mb-3 text-muted">Confira os itens antes de finalizar a compra.</h6>
      <div class="shopping-cart">
        <%= render 'shopping_cart' %>
      </div>
      
    </div>
  </div>

  <br><hr><br>

  <h3>Preço total do pedido: <span class="text-success" id="cart-text"><%= number_to_currency cart_total_price, unit: "R$ " %></span></h3>

</div>

<div class="container mb-4">
  <% if user_signed_in? %>
    <%= link_to "finalizar e pagar", carts_show_path, class: 'btn btn-success px-5' %>
  <% else %>
    <h4 class="mb-3"><small class="text-muted">Para finalizar o seu pedido, entre com sua conta ou faça cadastro.</small></h4>
    <%= link_to "Sign In", new_user_session_path, :method => :get, class: 'btn btn-success px-5' %>
    <%= link_to "Sign up", new_user_registration_path, :method => :get, class: 'btn btn-outline-success px-5' %>
  <% end %>
</div>
<br>

<%= render 'shared/footer' %>