config/routes.rb
Rails.application.routes.draw do
  
  root :to =>'home#index'
  devise_for :users,:controllers => { :registrations =>'users/registrations'}
  resources :users, except: [:create, :new, :show]
  resources :meal_categories, except: [:show]
  resources :meals
  resources :orders
  get 'carts/show'

  post 'order_meals', to: 'order_meals#create'
  patch 'order_meals', to: 'order_meals#update'
  delete 'order_meals', to: 'order_meals#destroy'
  
end

app/models/meal_category.rb
class MealCategory < ApplicationRecord
  has_many :meals, dependent: :destroy
  validates :name, presence: true, uniqueness: { case_sensitive: false }  
end

app/controllers/meal_categories_controller.rb
class MealCategoriesController < ApplicationController
  before_action :set_meal_category, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  before_action :authorize_admin

  # GET /meal_categories
  # GET /meal_categories.json
  def index
    @meal_categories = MealCategory.all
  end

  # GET /meal_categories/new
  def new
    @meal_category = MealCategory.new
  end

  # GET /meal_categories/1/edit
  def edit
  end

  # POST /meal_categories
  # POST /meal_categories.json
  def create
    @meal_category = MealCategory.new(meal_category_params)

    respond_to do |format|
      if @meal_category.save
        format.html { redirect_to meal_categories_path, notice: 'Meal category was successfully created.' }
        format.json { render :show, status: :created, location: @meal_category }
      else
        format.html { render :new }
        format.json { render json: @meal_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /meal_categories/1
  # PATCH/PUT /meal_categories/1.json
  def update
    respond_to do |format|
      if @meal_category.update(meal_category_params)
        format.html { redirect_to meal_categories_path, notice: 'Meal category was successfully updated.' }
        format.json { render :show, status: :ok, location: @meal_category }
      else
        format.html { render :edit }
        format.json { render json: @meal_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /meal_categories/1
  # DELETE /meal_categories/1.json
  def destroy
    @meal_category.destroy
    respond_to do |format|
      format.html { redirect_to meal_categories_url, notice: 'Meal category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_meal_category
      @meal_category = MealCategory.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def meal_category_params
      params.require(:meal_category).permit(:name)
    end
end

app/helpers/meal_categories_helper.rb
module MealCategoriesHelper
end

app/views/meal_categories/_form.html.erb
<%= form_with(model: meal_category, local: true) do |form| %>
  <%= render 'shared/form_error', obj: meal_category %>

  <div class="row">
      <div class="form-group col">
    <%= form.label :name %>
    <%= form.text_field :name, class: 'form-control'  %>
      </div>
  </div>
  
  <div class="actions">
    <%= form.submit "Criar nova categoria",class: 'btn btn-success mr-3 px-4'  %>
    <%= link_to 'Voltar', meal_categories_path ,class: 'btn btn-secondary px-4' %>
  </div>
<% end %>


    </ul>
  </div>
</div>

app/views/meal_categories/_form2.html.erb
<%= form_with(model: meal_category, local: true) do |form| %>
  <%= render 'shared/form_error', obj: meal_category %>

  <div class="row">
      <div class="form-group col">
    <%= form.label :name %>
    <%= form.text_field :name, class: 'form-control'  %>
      </div>
    <div class="form-group col">
          <%= form.label :created_at %><br />
          <%= form.date_field :created_at, class: 'form-control', readonly: true %>
        </div>
  </div>
  
  <div class="actions">
    <%= form.submit "Atualizar categoria de refeição",class: 'btn btn-success mr-3 px-4'  %>
    <%= link_to 'Voltar', meal_categories_path ,class: 'btn btn-secondary px-4' %>
  </div>
<% end %>


    </ul>
  </div>
</div>

app/views/meal_categories/edit.html.erb
<%= render "shared/backOffice_header" %>
<%= render 'shared/backOffice_nav' %>

<div class="container text-muted py-5">

<h2>Editar Categoria</h2>

<%= render 'form2', meal_category: @meal_category %>

<%= render 'shared/footer' %>

app/views/meal_categories/index.html.erb
<%= render "shared/backOffice_header" %>
<%= render 'shared/backOffice_nav' %>

<div class="container pb-3 pt-4">
 <table class="ctable">

  <thead class="thead-light">
  <tr>
    <th>Nome</th>
    <th>Número de refeições</th>
    <th>Cadastrado em</th>
    <th></th>
    <th></th>
  </tr>
</thead>

  <tbody>
    <% @meal_categories.each do |meal_category| %>
      <tr>
        <td><%= meal_category.name %></td>
        <td><%= meal_category.meals.count %></td>
        <td><%= meal_category.created_at.strftime("%d/%m/%y")%></td>
        <td><%= link_to 'Editar', edit_meal_category_path(meal_category), class: 'text-warning' %></td>
        <td><%= link_to 'Deletar', meal_category, method: :delete, data: { confirm: 'Are you sure?' }, class: 'text-danger' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nova categoria de refeição', new_meal_category_path , class: 'btn btn-success mr-3 px-4' %>

</div>

<%= render 'shared/footer' %>

app/views/meal_categories/new.html.erb
<%= render "shared/backOffice_header" %>
<%= render 'shared/backOffice_nav' %>
<div class="container text-muted py-5">

<h5><strong>Nova Categoria de refeição</strong></h5>
<hr>
<%= render 'form', meal_category: @meal_category %>

</div>
<%= render 'shared/footer' %>