config/routes.rb
Rails.application.routes.draw do
  
  root :to =>'home#index'
  devise_for :users,:controllers => { :registrations =>'users/registrations'}
  resources :users, except: [:create, :new, :show]
  resources :meal_categories, except: [:show]
  resources :meals
  resources :orders
  get 'carts/show'

  post 'order_meals', to: 'order_meals#create'
  patch 'order_meals', to: 'order_meals#update'
  delete 'order_meals', to: 'order_meals#destroy'
  
end

app/models/meal.rb
class Meal < ApplicationRecord
  belongs_to :meal_category
  has_many :order_meals

  validates :name, presence: true
  validates :price, presence: true
  
  mount_uploader :image, ImageUploader

  default_scope { where(available: true) }

end

app/controllers/meals_controller.rb
class MealsController < ApplicationController
  before_action :set_meal, only: [:show, :edit, :update, :destroy]
  before_action :select_meal_category, only: [:new, :edit, :update, :create]
  before_action :authenticate_user!
  before_action :authorize_admin

  # GET /meals
  # GET /meals.json
  def index
    @meals = Meal.all
  end

  # GET /meals/1
  # GET /meals/1.json
  def show
  end

  # GET /meals/new
  def new
    @meal = Meal.new
  end

  # GET /meals/1/edit
  def edit
  end

  # POST /meals
  # POST /meals.json
  def create
    @meal = Meal.new(meal_params)

    respond_to do |format|
      if @meal.save
        format.html { redirect_to meals_path, notice: 'Refeição criada com sucesso!' }
        format.json { render :show, status: :created, location: @meals_path }
      else
        format.html { render :new }
        format.json { render json: @meal.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /meals/1
  # PATCH/PUT /meals/1.json
  def update
    respond_to do |format|
      if @meal.update(meal_params)
        format.html { redirect_to meals_path, notice: 'Refeição atualizada com sucesso!' }
        format.json { render :show, status: :ok, location: @meals_path }
      else
        format.html { render :edit }
        format.json { render json: @meal.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /meals/1
  # DELETE /meals/1.json
  def destroy
    @meal.destroy
    respond_to do |format|
      format.html { redirect_to meals_url, notice: 'Refeição excluida!' }
      format.json { head :no_content }
    end
  end

  private

    def select_meal_category
      @select_meal_category = MealCategory.all
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_meal
      @meal = Meal.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def meal_params
      params.require(:meal).permit(:name, :meal_category_id, :description, :price, :available, :image)
    end
end

app/helpers/meals_helper.rb
module MealsHelper
end

app/views/meals/_form.html.erb
<%= form_with(model: meal, local: true, html: {multipart: true}) do |form| %>
  <%= render 'shared/form_error', obj: meal %>

  <div class="row">
      <div class="field col">
        <%= form.label :name, "Nome"%>
        <%= form.text_field :name, class: "form-control"%>
      </div>

      <div class="field col">
        <%= form.label :meal_category_id, "Categoria"%>
        <%= collection_select(:meal, :meal_category_id,  @select_meal_category, :id, :name, {}, {:class=>'form-control'})%>
      </div>
  </div>

  <br>

  <div>
      <div class="field">
        <%= form.label :description, "Descrição"%>
        <%= form.text_field :description, class: "form-control", id:"exampleFormControlTextarea1" %>
      </div>
  </div>

  <br>

  <div class="row">
      <div class="field col">
        <%= form.label :price, "Preço"%>
        <%= form.text_field :price, class: "form-control" %>
      </div>

      <div class="field col">
        <%= form.label :image, "Imagem" %><br>
        <div class="custom-file">
          <%= form.file_field :image, class: "form-control input-group-text" %>
        </div>
    </div>
  </div>

  <br>

  <div class="field">
      <%= form.check_box "available", {checked: false} if !current_page?('/meals/new')%>
      <%= form.label :available, "Esta refeição não estará disponível no cardápio" if !current_page?('/meals/new')%>
  </div>

  <div class="actions buttons-position mt-4">
      <%= form.submit 'criar refeição', class: "btn btn-success buttons-new" if current_page?('/meals/new')%> 
      <%= form.submit 'atualizar refeição', class: "btn btn-success buttons-new" if !current_page?('/meals/new') %>
      <%= link_to 'voltar', meals_path, class: "btn btn-secondary buttons-new back-position"%>
  </div>
<% end %>

app/views/meals/edit.html.erb
<%= render "shared/backOffice_header" %>
<%= render 'shared/backOffice_nav' %>
<div class="container text-muted py-5">
<h5>Editar refeição</h5>
<hr>

<%= render 'form', meal: @meal %>
</div>

app/views/meals/index.html.erb
<%= render "shared/backOffice_header" %>
<%= render 'shared/backOffice_nav' %>

<!--
<div class="container pb-3 pt-4">
<table class="ctable">
  <thead class="thead-light">
    <tr>
      <th>Nome</th>
      <th>Categoria</th>
      <th>Preço</th>
      <th>Disponivel</th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @meals.each do |meal| %>
      <tr>
        <td><%= meal.name %></td>
        <td><%= meal.meal_category.name%></td>
        <td>R$ <%= meal.price %></td>
        <td><%= meal.available %></td>
        <td><%= link_to 'editar', edit_meal_path(meal) %></td>
        <td><%= link_to 'excluir', meal, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nova refeição', new_meal_path , class: 'btn btn-success mr-3 px-4' %>

</div>

<%= render 'shared/footer' %>

-->

<div class="container my-5">
      <% @meals.in_groups_of(4, false) do |group| %>
      <div class="card-deck">
      <% group.each do |meal| %>
        <div class="card w-25">
          <div class="position-relative">
            <%= image_tag "#{meal.image}", alt: '', class: 'card-img-top' %>
            <div class="card-img-overlay h-100 d-flex flex-column justify-content-end p-0">
              <h5 class="bg-dark-50 mb-0 text-white p-2"><%= meal.name %></h5>
            </div>
          </div>
          <div class="card-body">
            <h6 class="card-subtitle mb-2 text-muted"><%= meal.description %></h6>
            <p class="card-text text-success"><strong>R$ <%= number_with_precision(meal.price, :precision => 2) %> por porção</strong></p>
          </div>
          <div class="row card-body">
            <div class="col">
              <%= link_to 'editar', edit_meal_path(meal), class: "btn btn-warning mr-2 px-4 btn-sm btn-block" %>
              <%= link_to 'excluir', meal, class: "btn btn-danger mr-2 px-4 btn-sm btn-block", method: :delete, data: { confirm: 'Are you sure?' } %>
            </div>
          </div>
        </div>
      <% end %>
      </div>
      <br>
      <% end %>
  <br>
  <%= link_to 'Nova refeição', new_meal_path , class: 'btn btn-success mr-3 px-4' %>
  </div>
  <%= render 'shared/footer' %>   

app/views/meals/new.html.erb
<%= render "shared/backOffice_header" %>
<%= render 'shared/backOffice_nav' %>
<div class="container text-muted py-5">
<h5><strong>Nova refeição</strong></h5>
<hr>
<%# criar um form sem por nada da um error estranho %>
<%= render 'form', meal: @meal %>

</div>
<%= render 'shared/footer' %>

app/views/meals/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @meal.name %>
</p>

<p>
  <strong>Categorium:</strong>
  <%= @meal.categorium %>
</p>

<p>
  <strong>Description:</strong>
  <%= @meal.description %>
</p>

<p>
  <strong>Price:</strong>
  <%= @meal.price %>
</p>

<p>
  <strong>Available:</strong>
  <%= @meal.available %>
</p>

<%= link_to 'Editar', edit_meal_path(@meal) %> |
<%= link_to 'Voltar', meals_path, class: "btn btn-secondary" %>